model:
  type: 'simclr'
  infonce_weight: 1.0
  vicreg_weight: 0.1
  barlowtwins_weight: 0.0
  representations_losses: [false, false, false]
  embeddings_losses: [true, true, false]
training:
  batch_size: 256
data:
  train: './data/voxceleb1_train_list'
  wav_augment:
    enable: true