model:
  type: 'simclr'
  infonce_weight: 0.0
  vicreg_weight: 1.0
  barlowtwins_weight: 0.0
  vic_inv_weight: 1.0
  vic_var_weight: 1.0
  vic_cov_weight: 0.1
training:
  batch_size: 256
data:
  train: './data/voxceleb1_train_list'
  wav_augment:
    enable: true